services:
  app:
    build:
      context: .
    environment:
      - GEO_USERNAME
      - GEO_PASSWORD
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_HOSTNAME
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
    logging:
      driver: local
